### PR TITLE
Properly label projects ending in X months

### PR DESCRIPTION
**Pull request by mzlock**
#36

### CODE REVIEW

**Comment by mzlock** [comment]
@brianjlandau - good to merge?

**Comment by RBFraxinus** [comment]
@mzlock The 3,6,12 month template logic looks like it will miss any projects that end exactly 3 or 6 months from the reference date.  Perhaps the 6 mo template needs a ">= 3 months" and "<= 6 months" to avoid that gap?

**Comment by mzlock** [comment]
@RBFraxinus that'd be a good thing to run by @brianjlandau 

@brianjlandau - mind taking a look?

**Comment by brianjlandau** [comment]
@RBFraxinus how's this look now?

**Pull request merged**
